greeting:
  value: Yaml

server:
  port: ${port:0}

spring:
  application:
    name: resttwo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
